// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC1_i-RosF5uIxNuD23ua49aKqMojArz9s',
    appId: '1:426215811881:web:91c732fc7e20e29c76a538',
    messagingSenderId: '426215811881',
    projectId: 'spotify-6d1da',
    authDomain: 'spotify-6d1da.firebaseapp.com',
    storageBucket: 'spotify-6d1da.appspot.com',
    measurementId: 'G-X4NMMP5MSH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-4y81MeRWzelO4FhTECLdUqbIz5Ycrb4',
    appId: '1:426215811881:android:55e4471dd1ff972b76a538',
    messagingSenderId: '426215811881',
    projectId: 'spotify-6d1da',
    storageBucket: 'spotify-6d1da.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAbOhfNWCWOQOxS0ZMqRU3iGBuwEia-A3U',
    appId: '1:426215811881:ios:a450b58ef2e38ce276a538',
    messagingSenderId: '426215811881',
    projectId: 'spotify-6d1da',
    storageBucket: 'spotify-6d1da.appspot.com',
    iosBundleId: 'com.example.spotifyBloc',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAbOhfNWCWOQOxS0ZMqRU3iGBuwEia-A3U',
    appId: '1:426215811881:ios:a450b58ef2e38ce276a538',
    messagingSenderId: '426215811881',
    projectId: 'spotify-6d1da',
    storageBucket: 'spotify-6d1da.appspot.com',
    iosBundleId: 'com.example.spotifyBloc',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC1_i-RosF5uIxNuD23ua49aKqMojArz9s',
    appId: '1:426215811881:web:bf009fe79965fc8276a538',
    messagingSenderId: '426215811881',
    projectId: 'spotify-6d1da',
    authDomain: 'spotify-6d1da.firebaseapp.com',
    storageBucket: 'spotify-6d1da.appspot.com',
    measurementId: 'G-4PXK2K17BL',
  );
}
